### ISSUE TITLE
Last commit broke deployment

### ISSUE THREAD

**Issue by sjamaan** [CodeYellowBV/django-binder#109]
As I tried to clone a project which uses Binder's latest commit, I got this nasty error:

```
Cloning https://github.com/CodeYellowBV/django-binder.git (to ffb3678a8a85f33a09afdc343bfb681c49d2c049) to /tmp/pip-build-a9m0862i/django-binder
Exception:
Traceback (most recent call last):
  File "/tmp/build.aaa-lux_vwu_o6yi/app/venv/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/tmp/build.aaa-lux_vwu_o6yi/app/venv/lib/python3.5/site-packages/pip/commands/download.py", line 198, in run
    requirement_set.prepare_files(finder)
  File "/tmp/build.aaa-lux_vwu_o6yi/app/venv/lib/python3.5/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/tmp/build.aaa-lux_vwu_o6yi/app/venv/lib/python3.5/site-packages/pip/req/req_set.py", line 638, in _prepare_file
    req_to_install.archive(self.download_dir)
  File "/tmp/build.aaa-lux_vwu_o6yi/app/venv/lib/python3.5/site-packages/pip/req/req_install.py", line 817, in archive
    zip.write(filename, self.name + '/' + name)
  File "/usr/lib/python3.5/zipfile.py", line 1435, in write
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-a9m0862i/django-binder/project/testapp'
```

This looks like something broke hard due to ffb3678a8a85f33a09afdc343bfb681c49d2c049. I have no clue what the hell is going on here. Please unbreak!

**Comment by Daanvdk** [comment]
Seems like that project folder contains a symlink to the testapp which was in the tests folder that was moved. Weird that this breaks since setup.py install works fine..

**Comment by Daanvdk** [comment]
Issue was with pip zipping the project which errors on faulty symlinks, symlink should be fixed now however.
